import { StyleSheet } from 'react-native';
import colors from '../../constants/colors';

const Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.BG_DARK,
  },
  content: {
    flex: 1,
    padding: 10,
  },
  createButton: {
    backgroundColor: colors.BG_BORDER,
    borderRadius: 50,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    shadowColor: colors.SHADOW,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
    position: 'absolute',
    bottom: 10,
    right: 15,
    zIndex: 1000,
  },
  createButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.TEXT_ON_PRIMARY,
  },
  listContainer: {
    flexGrow: 1,
  },
  listContent: {
    paddingBottom: 10,
  },
  userCard: {
    backgroundColor: colors.BG_CARD,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: colors.SHADOW,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 1,
    borderColor: colors.BG_BORDER,
  },
  userAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.PRIMARY,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  userAvatarText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.TEXT_ON_PRIMARY,
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.TEXT_PRIMARY,
    marginBottom: 4,
  },
  userDate: {
    fontSize: 12,
    color: colors.TEXT_SECONDARY,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyIcon: {
    fontSize: 60,
    marginBottom: 16,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.TEXT_PRIMARY,
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 14,
    color: colors.TEXT_LIGHT,
    textAlign: 'center',
  },
  menuButton: {
    padding: 6,
    marginLeft: 4,
  },
  overlay: {
    flex: 1,
  },
  popupMenu: {
    position: 'absolute',
    backgroundColor: colors.BG_ELEVATED,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.BG_BORDER,
    paddingVertical: 4,
    minWidth: 120,
    shadowColor: colors.SHADOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  popupMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  popupMenuText: {
    fontSize: 14,
    color: colors.TEXT_PRIMARY,
    fontWeight: '500',
  },
  popupMenuTextDanger: {
    color: colors.RED,
  },
  popupMenuDivider: {
    height: 1,
    backgroundColor: colors.BG_BORDER,
    marginHorizontal: 8,
  },
  deleteOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  deleteModal: {
    width: '100%',
    backgroundColor: colors.BG_CARD,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.BG_BORDER,
  },
  deleteIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 107, 107, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  deleteTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.TEXT_PRIMARY,
    marginBottom: 8,
  },
  deleteMessage: {
    fontSize: 14,
    color: colors.TEXT_SECONDARY,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  deleteUserName: {
    fontWeight: '700',
    color: colors.TEXT_PRIMARY,
  },
  deleteActions: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: colors.BG_ELEVATED,
    borderWidth: 1,
    borderColor: colors.BG_BORDER,
  },
  cancelButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.TEXT_PRIMARY,
  },
  deleteButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: colors.RED,
  },
  deleteButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#FFFFFF',
  },
});

export default Styles;
