import {
  Home,
  ArrowLeft,
  ArrowLeftRight,
  Users,
  User,
  Camera,
  BarChart2,
  UserPlus,
  Check,
  X,
  Image as ImageIcon,
  RefreshCw,
  ClipboardList,
  Calendar,
  EllipsisVertical,
  Pencil,
  Trash2,
  Wallet,
  Settings,
  UserCheck,
  UserX,
  Clock,
  ChevronRight,
  Bell,
  Scan,
  ScanFace,
  CheckCircle2,
  XCircle,
  ChartNoAxesCombined,
  CreditCard,
  Eye,
  Lock,
  Headphones,
  CircleQuestionMark,
  LogOut,
  Building2,
  SlidersHorizontal,
  Phone,
  ChevronDown,
  Download,
  MessageSquare,
} from 'lucide-react-native';

export const ICON_MAP = {
  home: Home,
  back: ArrowLeft,
  "arrow-left-right": ArrowLeftRight,
  users: Users,
  user: User,
  camera: Camera,
  chart: BarChart2,
  "user-plus": UserPlus,
  check: Check,
  close: X,
  image: ImageIcon,
  retake: RefreshCw,
  report: ClipboardList,
  calendar: Calendar,
  "more-vertical": EllipsisVertical,
  edit: Pencil,
  trash: Trash2,
  wallet: Wallet,
  settings: Settings,
  "user-check": UserCheck,
  "user-x": UserX,
  clock: Clock,
  "chevron-right": ChevronRight,
  bell: Bell,
  scan: Scan,
  "scan-face": ScanFace,
  "check-circle": CheckCircle2,
  "x-circle": XCircle,
  "chart-no-axes-combined": ChartNoAxesCombined,
  card: CreditCard,
  eye: Eye,
  lock: Lock,
  headphones: Headphones,
  help: CircleQuestionMark,
  logout: LogOut,
  building: Building2,
  sliders: SlidersHorizontal,
  phone: Phone,
  "chevron-down": ChevronDown,
  download: Download,
  feedback: MessageSquare,
} as const;

export type AppIconName = keyof typeof ICON_MAP;