import {
  Home,
  ArrowLeft,
  ArrowLeftRight,
  Users,
  User,
  Camera,
  BarChart2,
  UserPlus,
  Check,
  X,
  Image as ImageIcon,
  RefreshCw,
  ClipboardList,
  Calendar,
  EllipsisVertical,
  Pencil,
  Trash2,
} from 'lucide-react-native';

export const ICON_MAP = {
  home: Home,
  back: ArrowLeft,
  "arrow-left-right": ArrowLeftRight,
  users: Users,
  user: User,
  camera: Camera,
  chart: BarChart2,
  "user-plus": UserPlus,
  check: Check,
  close: X,
  image: ImageIcon,
  retake: RefreshCw,
  report: ClipboardList,
  calendar: Calendar,
  "more-vertical": EllipsisVertical,
  edit: Pencil,
  trash: Trash2,
} as const;

export type AppIconName = keyof typeof ICON_MAP;